import React from "react";
import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'aos';
import '@fontsource/poppins';
//import localFont from "next/font/local";
import "./styles/homepage.css";
import "./styles/utilities.css";
import "./styles/sign-in.css";
import './styles/complete-checkout.css';
import './styles/sign-up.css';
import './styles/sidebar.css';
//import 'aos';


export const metadata: Metadata = {
  title: "Top Up Gaming",
  description: "Generated by Rusdy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <head>
        </head>
        <body>
          {children} 
        </body>
    </html>
  );
}
